context:
  version: "5.0.9"

package:
  name: quasar-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@quasar/cli/-/cli-${{ version }}.tgz
  sha256: 12621501db19dc25f5272da5059e0a9eea61492b1936f3b898b889626d980dfa

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - quasar help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Quasar Framework - the Global CLI
  homepage: https://quasar.dev/
  repository: https://github.com/quasarframework/quasar

extra:
  recipe-maintainers:
    - danielnachun
