context:
  version: "5.0.6"

package:
  name: quasar-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@quasar/cli/-/cli-${{ version }}.tgz
  sha256: c9373eaf4884320b38626c425cef118efadbaded2da8ecbfa76f420a29e72bf5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - quasar help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Quasar Framework - the Global CLI
  homepage: https://quasar.dev/
  repository: https://github.com/quasarframework/quasar

extra:
  recipe-maintainers:
    - danielnachun
