context:
  version: "5.0.1"

package:
  name: quasar-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@quasar/cli/-/cli-${{ version }}.tgz
  sha256: b5e05780a90290eb25eb2dd15bdcfee82400e8887c357eec717bec1732a7609c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - quasar help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Quasar Framework - the Global CLI
  homepage: https://quasar.dev/
  repository: https://github.com/quasarframework/quasar

extra:
  recipe-maintainers:
    - danielnachun
